
use_colab: False

img_size: 128
img_size_recog: 128
batch_size: 16

detection_epochs: 50
detection_logging: False
detection_log_wieghts_interval: 5

recognition_epochs: 20
recognition_logging: False
recognition_log_wieghts_interval: 5

path_to_detection_weights: "/Users/andreisuhov/Downloads/18_checkpoint_detection.pth"

path_to_recognition_weights: "/Users/andreisuhov/Downloads/3_checkpoint_recognition (1).pth"





